
image: danielheh/nginx-k8s:1.0.0

replicaCount: 3

typeService: LoadBalancer

#minCountRep: 1
#maxCountRep: 2

#container:
#  requestsCpu: "100m"
#  requestsMemory: "128Mi"
#  limitsCpu: "350m"
#  limitsMemory: "256Mi"

