apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: web
  source:
    path: "chart"
    repoURL: "git@github.com:danielheh444/argo.git"
    targetRevision: HEAD
    helm:
      valuesFiles:
        - values_dev.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    